<a href="https://colab.research.google.com/github/vip21-000/data_analytics/blob/main/lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import pandas as pd
import numpy as np

print('pandas:', pd.__version__)
print('numpy:', np.__version__)

pandas: 2.2.3
numpy: 2.1.3

#Створення CSV та зчитування у DataFrame

In [14]:
data = {
    'date':    ['2025-09-01','2025-09-01','2025-09-01','2025-09-02','2025-09-02','2025-09-02','2025-09-03',
                '2025-09-03','2025-09-03','2025-09-04','2025-09-04','2025-09-05','2025-09-05'],
    'hour':    [8, 9, 12, 8, 10, 15, 9, 11, 17, 8, 13, 9, 18],
    'drink':   ['Latte','Espresso','Cappuccino','Americano','Latte','Mocha','Espresso','Cappuccino',
                'Latte','Americano','Mocha','Espresso','Cappuccino'],
    'payment': ['card','cash','card','card','cash','card','card','cash','card','cash','card','card','cash'],
    'money':   [55.0, 40.0, 50.0, 45.0, 55.0, 60.0, 40.0, 50.0, 55.0, 45.0, 60.0, 40.0, 50.0],
}
pd.DataFrame(data).to_csv('sales.csv', index=False)

df = pd.read_csv('sales.csv')
print('Перші 3 рядки:')
display(df.head(3))
print('Останні 3 рядки:')
display(df.tail(3))

Перші 3 рядки:

         date  hour       drink payment  money
0  2025-09-01     8       Latte    card   55.0
1  2025-09-01     9    Espresso    cash   40.0
2  2025-09-01    12  Cappuccino    card   50.0

Останні 3 рядки:

          date  hour       drink payment  money
10  2025-09-04    13       Mocha    card   60.0
11  2025-09-05     9    Espresso    card   40.0
12  2025-09-05    18  Cappuccino    cash   50.0

Назви колонок

In [15]:
cols = df.columns
print(cols)
print('Тип змінної:', type(cols))

Index(['date', 'hour', 'drink', 'payment', 'money'], dtype='object')
Тип змінної: <class 'pandas.core.indexes.base.Index'>

#Одновимірний масив

In [16]:
even = np.arange(2, 21, 2)
print('Масив:', even)
print('Сума:', even.sum())
print('Середнє:', even.mean())
print('Мінімум:', even.min())
print('Максимум:', even.max())
print('Помножений на 3:', even * 3)

Масив: [ 2  4  6  8 10 12 14 16 18 20]
Сума: 110
Середнє: 11.0
Мінімум: 2
Максимум: 20
Помножений на 3: [ 6 12 18 24 30 36 42 48 54 60]

#Двовимірний масив 3×3

In [17]:
m = np.random.randint(1, 11, size=(3, 3))
print('Матриця:\n', m)
print('Сума за стовпцями (axis=0):', m.sum(axis=0))
print('Сума за рядками (axis=1):', m.sum(axis=1))

Матриця:
 [[ 8  8  5]
 [ 9 10  8]
 [ 5  5  6]]
Сума за стовпцями (axis=0): [22 23 19]
Сума за рядками (axis=1): [21 27 16]

### Приклад форматування
Список переваг текстових комірок:
- пояснення поруч із кодом;
- **структурованість** ноутбука (заголовки, розділи);
- зручність для викладача та інших читачів.

**Переваги текстових комірок:** вони дозволяють документувати кожен крок аналізу, описувати висновки та мету коду, а також оформлювати ноутбук як повноцінний звіт, де код, результати й пояснення знаходяться в одному місці.

#Монтування Google Диска та зчитування CSV з Диска

In [18]:
from google.colab import drive
drive.mount('/content/drive')

# Для демонстрації копіюємо наш CSV на Диск (якщо файл там уже є — цей рядок можна пропустити)
df.to_csv('/content/drive/MyDrive/sales.csv', index=False)

df_drive = pd.read_csv('/content/drive/MyDrive/sales.csv')
df_drive.info()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   date     13 non-null     object
 1   hour     13 non-null     int64
 2   drink    13 non-null     object
 3   payment  13 non-null     object
 4   money    13 non-null     float64
dtypes: float64(1), int64(1), object(3)
memory usage: 652.0+ bytes

In [19]:
print('Типи з Диска:\n', df_drive.dtypes)
print('\nТипи з завдання 2:\n', df.dtypes)

Типи з Диска:
 date        object
hour         int64
drink       object
payment     object
money      float64
dtype: object

Типи з завдання 2:
 date        object
hour         int64
drink       object
payment     object
money      float64
dtype: object

#Додаткове завдання: повний цикл аналізу

**Крок 1.** Зчитуємо CSV з Диска та оглядаємо таблицю.

In [20]:
df = pd.read_csv('/content/drive/MyDrive/sales.csv')
display(df.head())
print('Розмірність:', df.shape)

         date  hour       drink payment  money
0  2025-09-01     8       Latte    card   55.0
1  2025-09-01     9    Espresso    cash   40.0
2  2025-09-01    12  Cappuccino    card   50.0
3  2025-09-02     8   Americano    card   45.0
4  2025-09-02    10       Latte    cash   55.0

Розмірність: (13, 5)

**Крок 2.** Типи даних і кількість непорожніх значень.

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   date     13 non-null     object
 1   hour     13 non-null     int64
 2   drink    13 non-null     object
 3   payment  13 non-null     object
 4   money    13 non-null     float64
dtypes: float64(1), int64(1), object(3)
memory usage: 652.0+ bytes

**Крок 3.** Основні статистики числових колонок.

In [22]:
df.describe()

            hour      money
count  13.000000  13.000000
mean   11.307692  49.615385
std     3.473342   7.205767
min     8.000000  40.000000
25%     9.000000  45.000000
50%    10.000000  50.000000
75%    13.000000  55.000000
max    18.000000  60.000000

**Крок 4.** Перетворюємо колонку `money` на масив NumPy і рахуємо середнє (середній чек).

In [23]:
money = df['money'].to_numpy()
print('Тип:', type(money))
print('Середній чек:', money.mean())

Тип: <class 'numpy.ndarray'>
Середній чек: 49.61538461538461

**Висновок:** середній чек можна отримати як через Pandas (`df['money'].mean()`), так і через NumPy — результат збігається.